[frontend]
4.224.17.171

[backend]
20.204.25.103

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
```

Then also check and share these files:
```
ansible/group_vars/backend.yaml
ansible/group_vars/frontend.yaml
